[package]
name = "compiler"
version = "0.0.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.3.0" }

index_vec = "0.1.3"
parking_lot = "0.12.1"
smallvec = { version = "2.0.0-alpha.1", features = ["specialization"] }

lexer = { path = "../lexer" }